### ISSUE TITLE
Generator not working

### ISSUE THREAD

**Issue by germs12** [apiaryio/Paw-APIBlueprintGenerator#15]
I am using `PAW 2.2.3 (Retail)` but the APIBlueprintGenerator is not working.  I opened the console and found the following error

```console
Error Cannot find module 'mustache.js' in require()
Event Loaded extension io.apiary.PawExtensions.APIBlueprintGenerator
JS Exception Line 101. ReferenceError: Can't find variable: Mustache
```

I uninstalled mustache.js via npm and reinstalled, but that didn't seem to fix anything.  Happy to try anything if you can give me some direction.  Thanks - love the tool! :+1:

**Comment by kylef** [comment]
Hi @germs12, unfortunately there was a backwards incompatible change in the latest Paw version for extension. We've updated the plugin and it's just pending release to the Paw extension site.

I'll let you know when this goes out, it should be tomorrow.

**Comment by germs12** [comment]
Awesome. Thank you so much!

**Comment by germs12** [comment]
@kylef Were you able to get the update out?

**Comment by kylef** [comment]
This is now out :balloon:.

**Comment by germs12** [comment]
@bemartinson926 @dhosterman 
:fireworks: Yahoo!!!
